services:
  app:
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app_name
    ipc: host
    command: sleep infinity
    volumes:
      - .:/app
      - ./.venv-container:/app/.venv
      - ${HF_HOME}:/huggingface
    tty: true
    environment:
      - HF_HOME=/huggingface
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
