services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app_name
    command: sleep infinity
    volumes:
      - .:/app
      - /app/.venv # https://docs.astral.sh/uv/guides/integration/docker/#mounting-the-project-with-docker-run
      - ${HF_HOME}:/huggingface
      - ${DATA_DIR}:/app/data
    tty: true
    env_file:
      - .env
    environment:
      - HF_HOME=${HF_HOME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
